#!/bin/bash

# Script for appending development log entries efficiently
# Usage: ./llm/append_log.sh [feature-name] "user|agent|action" "content"

# Default location for development logs
LOGS_DIR="llm/logs"

# Ensure logs directory exists
mkdir -p "$LOGS_DIR"

# Get feature name (defaults to general if not provided)
if [ -z "$1" ]; then
  FEATURE="general"
else
  FEATURE="$1"
fi

# Get current date for file organization
DATE=$(date +"%Y-%m-%d")

# Create feature directory if it doesn't exist
FEATURE_DIR="$LOGS_DIR/$FEATURE"
mkdir -p "$FEATURE_DIR"

# Define log file path
LOG_FILE="$FEATURE_DIR/$DATE-$FEATURE.txt"

# Create file if it doesn't exist with header
if [ ! -f "$LOG_FILE" ]; then
  echo "# Development Log: $FEATURE - $DATE" > "$LOG_FILE"
  echo "# Generated by append_log.sh" >> "$LOG_FILE"
  echo "" >> "$LOG_FILE"
fi

# Determine entry type and content
ENTRY_TYPE="$2"
CONTENT="$3"

# Append appropriate content based on entry type
case "$ENTRY_TYPE" in
  "user")
    echo "user: $CONTENT" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    ;;
  "agent")
    echo "agent: $CONTENT" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    ;;
  "action")
    # For action entries, we need justification and model
    MODEL="$4"
    echo "action: $CONTENT" >> "$LOG_FILE"
    echo "justification: $5" >> "$LOG_FILE"
    echo "model: $MODEL" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    ;;
  *)
    # For other custom entries, just append as is
    echo "$CONTENT" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    ;;
esac

echo "Log entry added to $LOG_FILE"

# List the most recent files for user convenience
echo ""
echo "Recent log files:"
find "$LOGS_DIR" -type f -name "*.txt" -mtime -7 | sort -r | head -5 